# Generated by Django 3.2.2 on 2021-05-09 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proteindata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxonomy',
            options={'verbose_name_plural': 'taxonomies'},
        ),
    ]
